---
- name: Download Hadoop Distribution
  get_url: url={{ distribution_link }} dest={{ install_directory }}/hadoop-{{hadoop_version}}.tar.gz mode=0777
  when: action == 'download' 

- name: Untar hadoop package
  shell: cd {{ install_directory }} && tar xzvf hadoop-{{ hadoop_version }}.tar.gz 

- name: Setup hadoop root dir
  file: path={{ install_directory }}/hadoop-{{ hadoop_version}} state=directory mode=0755 owner={{hadoop_user}} group={{hadoop_user}} recurse=yes
  
- name: Create Hadoop profile file
  file: path=/etc/profile.d/hadoop.sh state=touch mode=0755 owner=root group=root
  
- name: Set Hadoop global env vars
  lineinfile:
    create: yes
    dest: /etc/profile.d/hadoop.sh
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: true
  with_items:
    - { regexp: '^export JAVA_HOME', line: 'export JAVA_HOME={{java_home}}' }
    - { regexp: '^export HADOOP_INSTALL', line: 'export HADOOP_INSTALL={{install_directory}}/hadoop-{{hadoop_version}}' }
    - { regexp: '^export HADOOP_HOME=\$HADOOP_INSTALL', line: 'export HADOOP_INSTALL=$HADOOP_INSTALL' }
    - { regexp: '^export PATH=\$PATH:\$HADOOP_INSTALL/bin', line: 'export PATH=$PATH:$HADOOP_INSTALL/bin' }
    - { regexp: '^export PATH=\$PATH:\$HADOOP_INSTALL/sbin', line: 'export PATH=$PATH:$HADOOP_INSTALL/sbin' }
    - { regexp: '^export HADOOP_MAPRED_HOME=\$HADOOP_INSTALL', line: 'export HADOOP_MAPRED_HOME=$HADOOP_INSTALL' }
    - { regexp: '^export HADOOP_COMMON_HOME=\$HADOOP_INSTALL', line: 'export HADOOP_COMMON_HOME=$HADOOP_INSTALL' }
    - { regexp: '^export HADOOP_HDFS_HOME=\$HADOOP_INSTALL', line: 'export HADOOP_HDFS_HOME=$HADOOP_INSTALL' }
    - { regexp: '^export HADOOP_COMMON_LIB_NATIVE_DIR=\$HADOOP_INSTALL/lib/native', line: 'export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_INSTALL/lib/native' }
    - { regexp: '^export HADOOP_OPTS="-Djava.library.path=\$HADOOP_INSTALL/lib"', line: 'export HADOOP_OPTS="-Djava.library.path=$HADOOP_INSTALL/lib"' } 
    - { regexp: '^export HADOOP_CLASSPATH=\$HADOOP_CLASSPATH:\$HADOOP_INSTALL/share/hadoop/tools/lib/', line: 'export HADOOP_CLASSPATH=$HADOOP_CLASSPATH:$HADOOP_INSTALL/share/hadoop/tools/lib/*' }
- name: Create link to hadoop bin
  file: src={{ install_directory }}/hadoop-{{ hadoop_version}} dest={{install_directory}}/hadoop force=true state=link mode=0755 owner={{hadoop_user}} group={{hadoop_user}}
