---
- name: Download Hadoop Distribution
  get_url: url={{ distribution_link }} dest={{ install_directory }} mode=0777
  when: action == 'download' 

- name: Untar hadoop package
  shell: cd {{ install_directory }} && tar xzvf hadoop-{{ hadoop_version }}.tar.gz && mv hadoop-{{ hadoop_version }} hadoop
  
- name: Create link to hadoop bin
  file: src={{ install_directory }}/hadoop/bin/hadoop dest={{/usr/local/bin/hadoop}} force=true state=link
