---
- name: Download Hadoop Distribution
  get_url: url={{ distribution_link }} dest={{ install_directory }} mode=0777
  when: action == 'download' 

- name: Untar hadoop package
  shell: cd {{ install_directory }} && tar xzvf hadoop-{{ hadoop_version }}.tar.gz 
  
- name: Set some kernel parameters
  lineinfile:
    dest: /home/{{hadoop_user}}
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^export JAVA_HOME', line: 'export JAVA_HOME={{java_home}}' }
    - { regexp: '^export HADOOP_INSTALL', line: 'export HADOOP_INSTALL={{install_directory}}/hadoop-{{hadoop_version}}' }
    - { regexp: '^export PATH=$PATH:$HADOOP_INSTALL/bin', line: 'export PATH=$PATH:$HADOOP_INSTALL/bin' }
    - { regexp: '^export PATH=$PATH:$HADOOP_INSTALL/sbin', line: 'export PATH=$PATH:$HADOOP_INSTALL/sbin' }
    - { regexp: '^export HADOOP_MAPRED_HOME=$HADOOP_INSTALL', line: 'export HADOOP_MAPRED_HOME=$HADOOP_INSTALL' }
    - { regexp: '^export HADOOP_COMMON_HOME=$HADOOP_INSTALL', line: 'export HADOOP_COMMON_HOME=$HADOOP_INSTALL' }
    - { regexp: '^export HADOOP_HDFS_HOME=$HADOOP_INSTALL', line: 'export HADOOP_HDFS_HOME=$HADOOP_INSTALL' }
    - { regexp: '^export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_INSTALL/lib/native', line: 'export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_INSTALL/lib/native' }
    - { regexp: '^export HADOOP_OPTS="-Djava.library.path=$HADOOP_INSTALL/lib"', line: 'export HADOOP_OPTS="-Djava.library.path=$HADOOP_INSTALL/lib"' } 
    
#- name: Create link to hadoop bin
#  file: src={{ install_directory }}/hadoop-{{ hadoop_version}}/bin/hadoop dest=/usr/local/bin/hadoop force=true state=link
export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
export HADOOP_INSTALL=/usr/local/hadoop
export PATH=$PATH:$HADOOP_INSTALL/bin
export PATH=$PATH:$HADOOP_INSTALL/sbin
export HADOOP_MAPRED_HOME=$HADOOP_INSTALL
export HADOOP_COMMON_HOME=$HADOOP_INSTALL
export HADOOP_HDFS_HOME=$HADOOP_INSTALL
export YARN_HOME=$HADOOP_INSTALL
export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_INSTALL/lib/native
export HADOOP_OPTS="-Djava.library.path=$HADOOP_INSTALL/lib"
