---
- name: Download Hadoop Distribution
  get_url: url={{ distribution_link }} dest={{ install_directory }} mode=0777
  when: action == 'download' 

- name: Untar hadoop package
  shell: cd {{ install_directory }} && tar xzvf hadoop-{{ hadoop_version }}.tar.gz 
  
- name: Set Hadoop global env vars
  lineinfile:
    dest: /etc/environment
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^JAVA_HOME', line: 'JAVA_HOME={{java_home}}' }
    - { regexp: '^HADOOP_INSTALL', line: 'HADOOP_INSTALL={{install_directory}}/hadoop-{{hadoop_version}}' }
    - { regexp: '^PATH=\$PATH:\$HADOOP_INSTALL/bin', line: 'PATH=$PATH:$HADOOP_INSTALL/bin' }
    - { regexp: '^PATH=\$PATH:\$HADOOP_INSTALL/sbin', line: 'PATH=$PATH:$HADOOP_INSTALL/sbin' }
    - { regexp: '^HADOOP_MAPRED_HOME=\$HADOOP_INSTALL', line: 'HADOOP_MAPRED_HOME=$HADOOP_INSTALL' }
    - { regexp: '^HADOOP_COMMON_HOME=\$HADOOP_INSTALL', line: 'HADOOP_COMMON_HOME=$HADOOP_INSTALL' }
    - { regexp: '^HADOOP_HDFS_HOME=\$HADOOP_INSTALL', line: 'HADOOP_HDFS_HOME=$HADOOP_INSTALL' }
    - { regexp: '^HADOOP_COMMON_LIB_NATIVE_DIR=\$HADOOP_INSTALL/lib/native', line: 'HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_INSTALL/lib/native' }
    - { regexp: '^HADOOP_OPTS="-Djava.library.path=\$HADOOP_INSTALL/lib"', line: 'HADOOP_OPTS="-Djava.library.path=$HADOOP_INSTALL/lib"' } 
    
#- name: Create link to hadoop bin
#  file: src={{ install_directory }}/hadoop-{{ hadoop_version}}/bin/hadoop dest=/usr/local/bin/hadoop force=true state=link

