- name: Setting permissions for log directory
  file: path={{ install_directory}}/ mode=0777 state=directory recurse=yes

- name: Start NameNode
  shell: "{{ install_directory }}/hadoop/sbin/hadoop-daemon.sh --config {{ install_directory }}/hadoop/etc/hadoop --script hdfs start namenode"
  ignore_errors: yes
  register: command_result
  when: action == "start_namenode" 
  
- debug: msg="{{command_result}}"

- name: Start Slave
  shell: "HADOOP_SECURE_DN_USER=hdfs {{ install_directory }}/hadoop/sbin/hadoop-daemon.sh --config {{ install_directory }}/hadoop/etc/hadoop --script hdfs start datanode"
  register: command_result
  ignore_errors: yes
  when: action == "start_slave"

- debug: msg="{{command_result}}"

