- name: Setting permissions for log directory
  become: yes
  become_user: root
  file: path={{ install_directory}}/hadoop/logs mode=0777 state=directory

- name: Start NameNode
  become: yes
  become_user: hdfs
  shell: "{{ install_directory }}/hadoop/sbin/hadoop-daemon.sh --config {{ install_directory }}/hadoop/etc/hadoop --script hdfs start namenode"
  register: command_result
  failed_when: "'stderr:' in command_result.stderr"
  when: action == "start_namenode" 
  
- debug: msg="{{command_result.stderr}}"

- name: Start Slave
  become: yes
  become_user: root
  shell: "HADOOP_SECURE_DN_USER=hdfs {{ install_directory }}/hadoop/sbin/hadoop-daemon.sh --config {{ install_directory }}/hadoop/etc/hadoop --script hdfs start datanode"
  register: command_result
  failed_when: "'stderr:' in command_result.stderr"
  when: action == "start_slave"

- debug: msg="{{command_result.stderr}}"

- name: Start ResourceManager
  become: yes
  become_user: yarn
  shell: "{{ install_directory }}/hadoop/sbin/yarn-daemon.sh --config {{ install_directory }}/hadoop/etc/hadoop start resourcemanager" 
  register: command_result
  failed_when: "'stderr:' in command_result.stderr"
  when: action == "start_resource_manager"

- debug: msg="{{command_result.stderr}}"

- name: Start WebAppProxy
  become: yes
  become_user: yarn
  shell: "{{ install_directory }}/hadoop/bin/yarn start proxyserver --config {{ install_directory }}/hadoop/etc/hadoop"
  register: command_result
  failed_when: "'stderr:' in command_result.stderr"
  when: action == "start_webapp_proxy"

- debug: msg="{{command_result.stderr}}"

- name: Start JobHistoryServer
  become: yes
  become_user: mapred
  command: "{{ install_directory }}/hadoop/sbin/mr-jobhistory-daemon.sh start historyserver --config {{ install_directory }}/hadoop/etc/hadoop"
  register: command_result
  failed_when: "'stderr:' in command_result.stderr"
  when: action == "start_jobhistory_server"

- debug: msg="{{command_result.stderr}}"
